In [34]:
import numpy as np

In [35]:
a = np.array([[1,2,3,3,1],[6,8,11,10,7]])

In [36]:
a.resize(5,2)

In [37]:
a

array([[ 1,  2],
       [ 3,  3],
       [ 1,  6],
       [ 8, 11],
       [10,  7]])

In [38]:
a[1,0] = 2

In [39]:
a[2,0] = 3

In [40]:
a[3,0] = 3

In [41]:
a[4,0] = 1

In [42]:
a

array([[ 1,  2],
       [ 2,  3],
       [ 3,  6],
       [ 3, 11],
       [ 1,  7]])

In [50]:
a[0,1] = 6

In [44]:
a[1,1] = 8

In [47]:
a[2,1] = 11

In [52]:
a[3,1] = 10

In [54]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [55]:
mean_a = a.mean(axis = 0)

In [56]:
mean_a

array([2. , 8.4])

In [57]:
a_centered = a - mean_a

In [60]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [62]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [63]:
a_centered_sp

8.0

In [64]:
a_centered_sp / a.shape[0] - 1

0.6000000000000001

In [65]:
np.cov(a.T)[0,1]

2.0